/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CidadaoConsultaRouteImport } from './routes/cidadao.consulta'
import { Route as CidadaoDenunciaRouteImport } from './routes/cidadao.denuncia'
import { Route as PortalAcessosRouteImport } from './routes/portal.acessos'
import { Route as PortalAuditoriasRouteImport } from './routes/portal.auditorias'
import { Route as PortalAvaliadoresRouteImport } from './routes/portal.avaliadores'
import { Route as PortalCertificacoesRouteImport } from './routes/portal.certificacoes'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalDenunciasRouteImport } from './routes/portal.denuncias'
import { Route as PortalInstituicoesRouteImport } from './routes/portal.instituicoes'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalModelosRouteImport } from './routes/portal.modelos'
import { Route as PortalPlanoRouteImport } from './routes/portal.plano'
import { Route as PortalRegistrosRouteImport } from './routes/portal.registros'
import { Route as PortalRelatoriosRouteImport } from './routes/portal.relatorios'
import { Route as CidadaoInstituicaoIdRouteImport } from './routes/cidadao.instituicao.$id'
import { Route as PortalDenunciasProtocoloRouteImport } from './routes/portal.denuncias_.$protocolo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoConsultaRoute = CidadaoConsultaRouteImport.update({
  id: '/cidadao/consulta',
  path: '/cidadao/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoDenunciaRoute = CidadaoDenunciaRouteImport.update({
  id: '/cidadao/denuncia',
  path: '/cidadao/denuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAcessosRoute = PortalAcessosRouteImport.update({
  id: '/portal/acessos',
  path: '/portal/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAuditoriasRoute = PortalAuditoriasRouteImport.update({
  id: '/portal/auditorias',
  path: '/portal/auditorias',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAvaliadoresRoute = PortalAvaliadoresRouteImport.update({
  id: '/portal/avaliadores',
  path: '/portal/avaliadores',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCertificacoesRoute = PortalCertificacoesRouteImport.update({
  id: '/portal/certificacoes',
  path: '/portal/certificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDenunciasRoute = PortalDenunciasRouteImport.update({
  id: '/portal/denuncias',
  path: '/portal/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInstituicoesRoute = PortalInstituicoesRouteImport.update({
  id: '/portal/instituicoes',
  path: '/portal/instituicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalModelosRoute = PortalModelosRouteImport.update({
  id: '/portal/modelos',
  path: '/portal/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPlanoRoute = PortalPlanoRouteImport.update({
  id: '/portal/plano',
  path: '/portal/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRegistrosRoute = PortalRegistrosRouteImport.update({
  id: '/portal/registros',
  path: '/portal/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRelatoriosRoute = PortalRelatoriosRouteImport.update({
  id: '/portal/relatorios',
  path: '/portal/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadaoInstituicaoIdRoute = CidadaoInstituicaoIdRouteImport.update({
  id: '/cidadao/instituicao/$id',
  path: '/cidadao/instituicao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDenunciasProtocoloRoute =
  PortalDenunciasProtocoloRouteImport.update({
    id: '/portal/denuncias_/$protocolo',
    path: '/portal/denuncias/$protocolo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cidadao/consulta': typeof CidadaoConsultaRoute
  '/cidadao/denuncia': typeof CidadaoDenunciaRoute
  '/portal/acessos': typeof PortalAcessosRoute
  '/portal/auditorias': typeof PortalAuditoriasRoute
  '/portal/avaliadores': typeof PortalAvaliadoresRoute
  '/portal/certificacoes': typeof PortalCertificacoesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/denuncias': typeof PortalDenunciasRoute
  '/portal/instituicoes': typeof PortalInstituicoesRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/modelos': typeof PortalModelosRoute
  '/portal/plano': typeof PortalPlanoRoute
  '/portal/registros': typeof PortalRegistrosRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/cidadao/instituicao/$id': typeof CidadaoInstituicaoIdRoute
  '/portal/denuncias/$protocolo': typeof PortalDenunciasProtocoloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cidadao/consulta': typeof CidadaoConsultaRoute
  '/cidadao/denuncia': typeof CidadaoDenunciaRoute
  '/portal/acessos': typeof PortalAcessosRoute
  '/portal/auditorias': typeof PortalAuditoriasRoute
  '/portal/avaliadores': typeof PortalAvaliadoresRoute
  '/portal/certificacoes': typeof PortalCertificacoesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/denuncias': typeof PortalDenunciasRoute
  '/portal/instituicoes': typeof PortalInstituicoesRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/modelos': typeof PortalModelosRoute
  '/portal/plano': typeof PortalPlanoRoute
  '/portal/registros': typeof PortalRegistrosRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/cidadao/instituicao/$id': typeof CidadaoInstituicaoIdRoute
  '/portal/denuncias/$protocolo': typeof PortalDenunciasProtocoloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cidadao/consulta': typeof CidadaoConsultaRoute
  '/cidadao/denuncia': typeof CidadaoDenunciaRoute
  '/portal/acessos': typeof PortalAcessosRoute
  '/portal/auditorias': typeof PortalAuditoriasRoute
  '/portal/avaliadores': typeof PortalAvaliadoresRoute
  '/portal/certificacoes': typeof PortalCertificacoesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/denuncias': typeof PortalDenunciasRoute
  '/portal/instituicoes': typeof PortalInstituicoesRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/modelos': typeof PortalModelosRoute
  '/portal/plano': typeof PortalPlanoRoute
  '/portal/registros': typeof PortalRegistrosRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/cidadao/instituicao/$id': typeof CidadaoInstituicaoIdRoute
  '/portal/denuncias_/$protocolo': typeof PortalDenunciasProtocoloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cidadao/consulta'
    | '/cidadao/denuncia'
    | '/portal/acessos'
    | '/portal/auditorias'
    | '/portal/avaliadores'
    | '/portal/certificacoes'
    | '/portal/dashboard'
    | '/portal/denuncias'
    | '/portal/instituicoes'
    | '/portal/login'
    | '/portal/modelos'
    | '/portal/plano'
    | '/portal/registros'
    | '/portal/relatorios'
    | '/cidadao/instituicao/$id'
    | '/portal/denuncias/$protocolo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cidadao/consulta'
    | '/cidadao/denuncia'
    | '/portal/acessos'
    | '/portal/auditorias'
    | '/portal/avaliadores'
    | '/portal/certificacoes'
    | '/portal/dashboard'
    | '/portal/denuncias'
    | '/portal/instituicoes'
    | '/portal/login'
    | '/portal/modelos'
    | '/portal/plano'
    | '/portal/registros'
    | '/portal/relatorios'
    | '/cidadao/instituicao/$id'
    | '/portal/denuncias/$protocolo'
  id:
    | '__root__'
    | '/'
    | '/cidadao/consulta'
    | '/cidadao/denuncia'
    | '/portal/acessos'
    | '/portal/auditorias'
    | '/portal/avaliadores'
    | '/portal/certificacoes'
    | '/portal/dashboard'
    | '/portal/denuncias'
    | '/portal/instituicoes'
    | '/portal/login'
    | '/portal/modelos'
    | '/portal/plano'
    | '/portal/registros'
    | '/portal/relatorios'
    | '/cidadao/instituicao/$id'
    | '/portal/denuncias_/$protocolo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CidadaoConsultaRoute: typeof CidadaoConsultaRoute
  CidadaoDenunciaRoute: typeof CidadaoDenunciaRoute
  PortalAcessosRoute: typeof PortalAcessosRoute
  PortalAuditoriasRoute: typeof PortalAuditoriasRoute
  PortalAvaliadoresRoute: typeof PortalAvaliadoresRoute
  PortalCertificacoesRoute: typeof PortalCertificacoesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDenunciasRoute: typeof PortalDenunciasRoute
  PortalInstituicoesRoute: typeof PortalInstituicoesRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalModelosRoute: typeof PortalModelosRoute
  PortalPlanoRoute: typeof PortalPlanoRoute
  PortalRegistrosRoute: typeof PortalRegistrosRoute
  PortalRelatoriosRoute: typeof PortalRelatoriosRoute
  CidadaoInstituicaoIdRoute: typeof CidadaoInstituicaoIdRoute
  PortalDenunciasProtocoloRoute: typeof PortalDenunciasProtocoloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao/consulta': {
      id: '/cidadao/consulta'
      path: '/cidadao/consulta'
      fullPath: '/cidadao/consulta'
      preLoaderRoute: typeof CidadaoConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao/denuncia': {
      id: '/cidadao/denuncia'
      path: '/cidadao/denuncia'
      fullPath: '/cidadao/denuncia'
      preLoaderRoute: typeof CidadaoDenunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/acessos': {
      id: '/portal/acessos'
      path: '/portal/acessos'
      fullPath: '/portal/acessos'
      preLoaderRoute: typeof PortalAcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/auditorias': {
      id: '/portal/auditorias'
      path: '/portal/auditorias'
      fullPath: '/portal/auditorias'
      preLoaderRoute: typeof PortalAuditoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/avaliadores': {
      id: '/portal/avaliadores'
      path: '/portal/avaliadores'
      fullPath: '/portal/avaliadores'
      preLoaderRoute: typeof PortalAvaliadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/certificacoes': {
      id: '/portal/certificacoes'
      path: '/portal/certificacoes'
      fullPath: '/portal/certificacoes'
      preLoaderRoute: typeof PortalCertificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/denuncias': {
      id: '/portal/denuncias'
      path: '/portal/denuncias'
      fullPath: '/portal/denuncias'
      preLoaderRoute: typeof PortalDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/instituicoes': {
      id: '/portal/instituicoes'
      path: '/portal/instituicoes'
      fullPath: '/portal/instituicoes'
      preLoaderRoute: typeof PortalInstituicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/modelos': {
      id: '/portal/modelos'
      path: '/portal/modelos'
      fullPath: '/portal/modelos'
      preLoaderRoute: typeof PortalModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/plano': {
      id: '/portal/plano'
      path: '/portal/plano'
      fullPath: '/portal/plano'
      preLoaderRoute: typeof PortalPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/registros': {
      id: '/portal/registros'
      path: '/portal/registros'
      fullPath: '/portal/registros'
      preLoaderRoute: typeof PortalRegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/relatorios': {
      id: '/portal/relatorios'
      path: '/portal/relatorios'
      fullPath: '/portal/relatorios'
      preLoaderRoute: typeof PortalRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidadao/instituicao/$id': {
      id: '/cidadao/instituicao/$id'
      path: '/cidadao/instituicao/$id'
      fullPath: '/cidadao/instituicao/$id'
      preLoaderRoute: typeof CidadaoInstituicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/denuncias_/$protocolo': {
      id: '/portal/denuncias_/$protocolo'
      path: '/portal/denuncias/$protocolo'
      fullPath: '/portal/denuncias/$protocolo'
      preLoaderRoute: typeof PortalDenunciasProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CidadaoConsultaRoute: CidadaoConsultaRoute,
  CidadaoDenunciaRoute: CidadaoDenunciaRoute,
  PortalAcessosRoute: PortalAcessosRoute,
  PortalAuditoriasRoute: PortalAuditoriasRoute,
  PortalAvaliadoresRoute: PortalAvaliadoresRoute,
  PortalCertificacoesRoute: PortalCertificacoesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDenunciasRoute: PortalDenunciasRoute,
  PortalInstituicoesRoute: PortalInstituicoesRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalModelosRoute: PortalModelosRoute,
  PortalPlanoRoute: PortalPlanoRoute,
  PortalRegistrosRoute: PortalRegistrosRoute,
  PortalRelatoriosRoute: PortalRelatoriosRoute,
  CidadaoInstituicaoIdRoute: CidadaoInstituicaoIdRoute,
  PortalDenunciasProtocoloRoute: PortalDenunciasProtocoloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
